[package]
name = "lz4-dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "0.4"
log = "0.4"
lzzzz = "1.0"
tar = "0.4"
thiserror = "1"
tempfile = "3.7.0"